{
 "title": "Mining",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "worker", "query": "label_values(worker)" },
   { "name": "pool", "query": "label_values(pool)" }
  ]
 },
 "panels": [
  {
   "title": "Activity Pool",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tarioch_poolmon_activity" }
   ]
  },
  {
   "title": "Current Balance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tarioch_poolmon_balance" }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tarioch_poolmon_balance) by (pool)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Daily (last 1d)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "clamp_min(deriv(tarioch_poolmon_income_total[1h]), 0) * 60 * 60 * 24"
    }
   ]
  },
  {
   "title": "Daily (last 1w)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "clamp_min(deriv(tarioch_poolmon_income_total[1d]), 0) * 60 * 60 * 24"
    }
   ]
  },
  {
   "title": "$worker Algo Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 5 },
   "repeat": "worker",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(tarioch_poolmon_activity{worker=\"$worker\"}[1d])",
     "legendFormat": "{{ algo }}"
    }
   ]
  },
  {
   "title": "$worker Algo Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(tarioch_poolmon_activity{worker=\"$worker\"}[1d])",
     "legendFormat": "{{ algo }}"
    }
   ]
  },
  {
   "title": "Daily 1h avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(deriv(tarioch_poolmon_balance[1h]), 0) * 60 * 60 * 24 ",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "$worker Algo Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 14 },
   "repeat": "worker",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(tarioch_poolmon_activity{worker=\"$worker\"}[1d])",
     "legendFormat": "{{ algo }}"
    }
   ]
  },
  {
   "title": "$worker Algo Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(tarioch_poolmon_activity{worker=\"$worker\"}[1d])",
     "legendFormat": "{{ algo }}"
    }
   ]
  },
  {
   "title": "Daily avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(deriv(tarioch_poolmon_balance[1d]), 0) * 60 * 60 * 24",
     "legendFormat": "{{ pool }}"
    }
   ]
  }
 ]
}