apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "poolmon.fullname" . }}
    labels:
        app: {{ template "poolmon.name" . }}
        chart: {{ template "poolmon.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    config.yaml: |-
{{ .Values.config | indent 4 }}

