apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "poolmon.name" . }}
  labels:
    app: {{ template "poolmon.name" . }}
    chart: {{ template "poolmon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "poolmon.name" . }}
  endpoints:
  - port: http
    path: /
    interval: 5m
    scrapeTimeout: 1m
